### ISSUE TITLE
WebHookBots cannot be registered

### ISSUE THREAD

**Issue by isopov** [xabgesagtx/telegram-spring-boot-starter#3]
In `TelegramBotAutoConfiguration` default `TelegramBotsApi` is created with no arguments meaning useWebhook == false. And thus method `registerBot(WebhookBot bot)` does nothing.

**Comment by xabgesagtx** [comment]
@isopov I fixed this by introducing new properties. Also, mentioned in edited Readme.md. Are webhooks working for you now?

If yes, I will do a release asap.

**Comment by xabgesagtx** [comment]
Created release 0.15 which includes the fixes
